
FROM python:3.12-slim-bookworm as base

COPY --from=ghcr.io/astral-sh/uv:0.6.9 /uv /uvx /bin/

RUN apt-get update && apt-get install -y s3fs && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./server.py server.py
COPY ./pyproject.toml pyproject.toml

RUN uv venv /opt/venv

ENV PATH=/opt/venv/bin:$PATH
ENV VIRTUAL_ENV=/opt/venv
ENV UV_PROJECT_ENVIRONMENT=/opt/venv

RUN uv sync --no-install-project

# Setup mount point
RUN mkdir /mnt/mybucket

# Copy the passwd-s3fs file to the mount point
COPY ./.passwd-s3fs /root/.passwd-s3fs

# Set the correct permissions for the passwd-s3fs file
RUN chmod 600 /root/.passwd-s3fs

EXPOSE 8000

CMD s3fs mybucket /mnt/mybucket -o url=http://minio:9000 -o use_path_request_style -o allow_other -o passwd_file=/root/.passwd-s3fs && \
    uvicorn server:app --host 0.0.0.0 --port 8000