[project]
name = "minio-fastapi-botoclient"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.36",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.1",
]
